
---

dotfiles_repo: "https://github.com/geerlingguy/dotfiles.git"
dotfiles_repo_accept_hostkey: false
dotfiles_repo_local_destination: "~/Documents/dotfiles"

dotfiles_home: "~"
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .vimrc
