---
# Is Apache installed?
- name: Check if "{{ apache_server_root }}" exists
  stat:
    path: "{{ apache_server_root }}"
  register: stat_tmp_2   # = true if apache is installed

# Is Apache installed?
- name: Check if "{{ apache_conf_path }}" exists
  stat:
    path: "{{ apache_conf_path }}"
  register: stat_tmp_3   # = true if apache is installed

- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/ports.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache
  when:
    - stat_tmp_2.stat.exists|bool == true

- name: Enable Apache mods.
  file:
    src: "{{ apache_server_root }}/mods-available/{{ item }}.load"
    dest: "{{ apache_server_root }}/mods-enabled/{{ item }}.load"
    state: link
    mode: 0644
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache
  when:
    - stat_tmp_2.stat.exists|bool == true

- name: Disable Apache mods.
  file:
    path: "{{ apache_server_root }}/mods-enabled/{{ item }}.load"
    state: absent
  with_items: "{{ apache_mods_disabled }}"
  notify: restart apache
  when:
    - stat_tmp_2.stat.exists|bool == true

- name: Check whether certificates defined in vhosts exist.
  stat: "path={{ item.certificate_file }}"
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: (apache_create_vhosts | bool) and (stat_tmp_3.stat.exists|bool == true)

- name: Add vhost symlink in sites-enabled.
  file:
    src: "{{ apache_conf_path }}/sites-available/{{ apache_vhosts_filename }}"
    dest: "{{ apache_conf_path }}/sites-enabled/{{ apache_vhosts_filename }}"
    state: link
    mode: 0644
  notify: restart apache
  when: (apache_create_vhosts | bool) and (stat_tmp_3.stat.exists|bool == true)

- name: Remove default vhost in sites-enabled.
  file:
    path: "{{ apache_conf_path }}/sites-enabled/{{ apache_default_vhost_filename }}"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost
