
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# task file for 'dev-tools' role - install useful devlopment utilities
#
# YAML linter to spot Ansible YAML syntax errors
#    yamllint playbook.yml roles/dev-tools/tasks
#
# Ansible linter to spot Ansible playbook syntax errors
#    ansible-playbook -i inventory -l test-pi playbook.yml --syntax-check
#
# Ansible dry-run to understand what task will be executed without making changes
#    ansible-playbook -i inventory -l test-pi  playbook.yml --tags dev-tools --skip-tags uninstall --list-tasks

---


# --- Install Block of Tasks ---------------------------------------------------

- name: Install Useful Devlopment Utilities
  block:
    - name: run the equivalent of "apt update" (as root)
      ansible.builtin.apt:
        state: latest            # must be one of: absent, build-dep, fixed, latest, present
        update_cache: true       # update the apt repository list cache
        cache_valid_time: 86400  # update the apt cache if it is older than this seconds

    - name: install general development tools (as root)
      ansible.builtin.apt:
        name: ['gnome-terminal', 'screen', 'telnet', 'jq', 'markdown']
        state: latest

    - name: install software version control tools (as root)
      ansible.builtin.apt:
        name: ['git', 'git-lfs']
        state: latest

    - name: install needed compilers (as root)
      ansible.builtin.apt:
        name: ['build-essential', 'cmake', 'unzip', 'pkg-config']
        state: latest

    - name: install ansible and yaml tools (as root)
      ansible.builtin.apt:
        name: ['yamllint', 'ansible-lint']
        state: latest

    - name: install X windows libraries and OpenGL libraries (as root)
      ansible.builtin.apt:
        name: ['libxmu-dev', 'libxi-dev', 'libglu1-mesa', 'libglu1-mesa-dev']
        state: latest

    - name: install optimization algorithums libraries (as root)
      ansible.builtin.apt:
        name: ['libopenblas-dev', 'libatlas-base-dev', 'liblapack-dev', 'gfortran']
        state: latest

    - name: install HDF5 library for working with large datasets (as root)
      ansible.builtin.apt:
        name: ['libhdf5-serial-dev']
        state: latest

    - name: install image and video libraries (as root)
      ansible.builtin.apt:
        name: ['libjpeg-dev', 'libpng-dev', 'libtiff-dev', 'libavcodec-dev', 'libavformat-dev', 'libswscale-dev', 'libv4l-dev', 'libxvidcore-dev', 'libx264-dev']
        state: latest

    - name: install node.js and npm (as root)
      ansible.builtin.apt:
        name: ['nodejs', 'npm']
        state: latest

    - name: install secure hash algorithms (SHA) tools, specifically SHA256 (as root)
      ansible.builtin.apt:
        name: ['hashalot']
        state: latest

    - name: install some X Window utilities (as root)
      ansible.builtin.apt:
        name: ['x11-apps', 'x11-xserver-utils', 'xterm', 'wmctrl']
        state: latest

    - name: install tools for viewing and manipulating image & video files (as root)
      ansible.builtin.apt:
        name: ['imagemagick', 'feh', 'mplayer']
        state: latest

    - name: install python 3 development libraries including TK and GTK GUI support (as root)
      ansible.builtin.apt:
        name: ['python3-dev', 'python3-tk', 'libgtk-3-dev', 'libboost-all-dev', 'python3-widgetsnbextension', 'python3-testresources', 'build-essential', 'cmake', 'python3-pip']
        state: latest
  tags: ['never', 'install']           # 'never' implies you must pass the tag to execute this block

# --- Uninstall Block of Tasks -------------------------------------------------

- name: Uninstall Useful Devlopment Utilities
  block:
    - name: message to user
      ansible.builtin.debug:
        msg: Nothing done. Packages newly installed and up-grades are unchanged.
  tags: ['never', 'uninstall']   # 'never' implies you must pass the other tag to execute this block

# ------------------------------------------------------------------------------

