
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      0.0.5
#
# YAML linter to spot Ansible YAML syntax errors
#    yamllint playbooks/dev-env
#    ansible-playbook -i inventory playbooks/dev-env/dev-env.yml --check --tags install
#
# Ansible linter to spot Ansible playbook syntax errors
#    ansible-playbook -i inventory playbooks/dev-env/dev-env.yml --syntax-check
#
# Ansible dry-run checking for errors and showing results of a run
#    ansible-playbook -i inventory playbooks/dev-env/dev-env.yml --check --tags install
#

---

- name: Create your login environment on {{ login_env_host }}
  hosts: "{{ login_env_host }}"
  # remote_user: "{{ app_user }}"
  become: true                   # set to 'true' to activate privilege escalation => use sudo and be root by default
  become_method: sudo
  gather_facts: true
  vars_files:
    - vars/default.yml

  tasks:
    # --------------------------------------------------------------------------
    - name: Install Tools for Development Environment
      block:
        - name: install needed compilers
          apt:
            state: latest            # must be one of: absent, build-dep, fixed, latest, present
            update_cache: true       # update the apt repository list cache
            cache_valid_time: 86400  # update the apt cache if it is older than this seconds
            pkg: ['build-essential', 'cmake', 'unzip', 'pkg-config', 'gcc', 'g++']

        - name: python 3 development libraries including TK and GTK GUI support
          apt:
            state: latest
            pkg: ['python3-dev', 'python3-tk', 'python-imaging-tk', 'libgtk-3-dev', 'libboost-all-dev', 'python3-widgetsnbextension', 'python3-testresources', 'build-essential', 'python3-pip']

        - name: install X windows libraries and OpenGL libraries
          apt:
            state: latest
            pkg: ['libxmu-dev', 'libxi-dev', 'libglu1-mesa', 'libglu1-mesa-dev']

        - name: install optimization algorithums libraries
          apt:
            state: latest
            pkg: ['libopenblas-dev', 'libatlas-base-dev', 'liblapack-dev', 'gfortran']

        - name: HDF5 library for working with large datasets
          apt:
            state: latest
            pkg: ['libhdf5-serial-dev']

        - name: install image and video libraries
          apt:
            state: latest
            pkg: ['libjpeg-dev', 'libpng-dev', 'libtiff-dev', 'libavcodec-dev', 'libavformat-dev', 'libswscale-dev', 'libv4l-dev', 'libxvidcore-dev', 'libx264-dev']

        - name: general development tools
          apt:
            state: latest
            pkg: ['gnome-terminal', 'jq', 'markdown', 'vim-gtk3', 'screen']

        - name: software version control tools
          apt:
            state: latest
            pkg: ['git', 'git-lfs']

        - name: install some networking tools
          apt:
            state: latest
            pkg: ['net-tools']

        - name: install node.js and npm
          apt:
            state: latest
            pkg: ['nodejs', 'npm']

        - name: secure hash algorithms (SHA) tools, specifically SHA256
          apt:
            state: latest
            pkg: ['hashalot']

        - name: install some X Window utilities
          apt:
            state: latest
            pkg: ['x11-apps', 'x11-xserver-utils', 'xterm', 'wmctrl']

        - name: tools for viewing and manipulating image & video files
          apt:
            state: latest
            pkg: ['imagemagick', 'feh', 'mplayer']

        - name: add google chrome apt signing key
          apt_key:
            url: "https://dl.google.com/linux/linux_signing_key.pub"
            state: present

        - name: add google chrome repository into sources list
          apt_repository:
            repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
            state: present
            filename: google-chrome

        - name: install google-chrome-stable - your favorite browser
          apt:
            state: latest
            update_cache: true
            pkg: ['google-chrome-stable']
      tags: ['never', 'install']     # 'never' implies you must pass the tag to execute this block

    # --------------------------------------------------------------------------
    - name: Uninstall Tools for Development Environment
      block:
        - name: uninstall google-chrome-stable
          apt:
            state: absent        # must be one of: absent, build-dep, fixed, latest, present
            autoclean: true      # cleans the local repository packages that can no longer be downloaded
            autoremove: true     # remove unused dependency with repository packages
            pkg: ['google-chrome-stable']
      tags: ['never', 'uninstall']   # 'never' implies you must pass the tag to execute this block

