
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# DESCRIPTION
#    Role file for 'dev-env' role - install useful development environments and tools
#
# TESTING
#    YAML linter to spot Ansible YAML syntax errors
#       yamllint rpi-loader.yml roles/dev-env/tasks
#       ansible-lint roles/dev-env/tasks/main.yml
#
#    Ansible linter to spot Ansible playbook syntax errors
#       ansible-playbook -i inventory -l test-pi rpi-loader.yml --syntax-check
#
#    Generate a list of tasks that will be executed for the tags
#       ansible-playbook -i inventory -l test-pi rpi-loader.yml --tags dev-env --skip-tags uninstall --list-tasks
#
#    Ansible dry-run checking for errors and showing results of a run
#       ansible-playbook -i inventory -l test-pi rpi-loader.yml --tags dev-env --skip-tags uninstall --check
#
# EXECUTION
#    Run the entire playbook for real
#       ansible-playbook -i inventory -l test-pi  rpi-loader.yml --tags dev-env --skip-tags uninstall
#
# SOURCES
#
#

---


# --- Install Block of Tasks ---------------------------------------------------

- name: Install Tools for Development Environment
  tags: ['never', 'install']     # 'never' implies you must pass the tag to execute this block
  block:
    - name: Install needed compilers (as root)
      ansible.builtin.apt:
        state: present           # must be one of: absent, build-dep, fixed, latest, present
        update_cache: true       # update the apt repository list cache
        cache_valid_time: 86400  # update the apt cache if it is older than this seconds
        pkg: ['build-essential', 'cmake', 'unzip', 'pkg-config', 'gcc', 'g++']

    - name: Install python 3 development libraries including TK and GTK GUI support (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['python3-dev', 'python3-tk', 'python-imaging-tk', 'libgtk-3-dev', 'libboost-all-dev', 'python3-widgetsnbextension', 'python3-testresources', 'build-essential', 'python3-pip']

    - name: Install X windows libraries and OpenGL libraries (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['libxmu-dev', 'libxi-dev', 'libglu1-mesa', 'libglu1-mesa-dev']

    - name: Install optimization algorithums libraries (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['libopenblas-dev', 'libatlas-base-dev', 'liblapack-dev', 'gfortran']

    - name: Install HDF5 library for working with large datasets (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['libhdf5-serial-dev']

    - name: Install image and video libraries (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['libjpeg-dev', 'libpng-dev', 'libtiff-dev', 'libavcodec-dev', 'libavformat-dev', 'libswscale-dev', 'libv4l-dev', 'libxvidcore-dev', 'libx264-dev']

    - name: Install general development tools (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['gnome-terminal', 'jq', 'markdown', 'vim-gtk3', 'screen']

    - name: Install software version control tools (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['git', 'git-lfs']

    - name: Install some networking tools (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['net-tools']

    - name: Install node.js and npm (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['nodejs', 'npm']

    - name: Install secure hash algorithms (SHA) tools, specifically SHA256 (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['hashalot']

    - name: Install some X Window utilities (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['x11-apps', 'x11-xserver-utils', 'xterm', 'wmctrl']

    - name: Install tools for viewing and manipulating image & video files (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['imagemagick', 'feh', 'mplayer']

    - name: Install chromium-browser (as root)
      ansible.builtin.apt:
        state: present
        pkg: ['chromium-browser']

# --- Uninstall Block of Tasks -------------------------------------------------

- name: Uninstall Tools for Development Environment
  tags: ['never', 'uninstall']   # 'never' implies you must pass the tag to execute this block
  block:
    - name: Uninstall chromium-browser (as root)
      ansible.builtin.apt:
        state: absent        # must be one of: absent, build-dep, fixed, latest, present
        autoclean: true      # cleans the local repository packages that can no longer be downloaded
        autoremove: true     # remove unused dependency with repository packages
        pkg: ['chromium-browser']

# ------------------------------------------------------------------------------

