
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# task file for 'dev-env' role - install useful development environments and tools
#
# YAML linter to spot Ansible YAML syntax errors
#    yamllint playbook.yml roles/dev-env/tasks
#
# Ansible linter to spot Ansible playbook syntax errors
#    ansible-playbook -i inventory -l test-pi playbook.yml --syntax-check
#
# Ansible dry-run to understand what task will be executed without making changes
#    ansible-playbook -i inventory -l test-pi  playbook.yml --tags dev-env --skip-tags uninstall --list-tasks

---


# --- Install Block of Tasks ---------------------------------------------------

- name: Install Tools for Development Environment
  block:
    - name: install needed compilers (as root)
      apt:
        state: latest            # must be one of: absent, build-dep, fixed, latest, present
        update_cache: true       # update the apt repository list cache
        cache_valid_time: 86400  # update the apt cache if it is older than this seconds
        pkg: ['build-essential', 'cmake', 'unzip', 'pkg-config', 'gcc', 'g++']

    - name: install python 3 development libraries including TK and GTK GUI support (as root)
      apt:
        state: latest
        pkg: ['python3-dev', 'python3-tk', 'python-imaging-tk', 'libgtk-3-dev', 'libboost-all-dev', 'python3-widgetsnbextension', 'python3-testresources', 'build-essential', 'python3-pip']

    - name: install X windows libraries and OpenGL libraries (as root)
      apt:
        state: latest
        pkg: ['libxmu-dev', 'libxi-dev', 'libglu1-mesa', 'libglu1-mesa-dev']

    - name: install optimization algorithums libraries (as root)
      apt:
        state: latest
        pkg: ['libopenblas-dev', 'libatlas-base-dev', 'liblapack-dev', 'gfortran']

    - name: install HDF5 library for working with large datasets (as root)
      apt:
        state: latest
        pkg: ['libhdf5-serial-dev']

    - name: install image and video libraries (as root)
      apt:
        state: latest
        pkg: ['libjpeg-dev', 'libpng-dev', 'libtiff-dev', 'libavcodec-dev', 'libavformat-dev', 'libswscale-dev', 'libv4l-dev', 'libxvidcore-dev', 'libx264-dev']

    - name: install general development tools (as root)
      apt:
        state: latest
        pkg: ['gnome-terminal', 'jq', 'markdown', 'vim-gtk3', 'screen']

    - name: install software version control tools (as root)
      apt:
        state: latest
        pkg: ['git', 'git-lfs']

    - name: install some networking tools (as root)
      apt:
        state: latest
        pkg: ['net-tools']

    - name: install node.js and npm (as root)
      apt:
        state: latest
        pkg: ['nodejs', 'npm']

    - name: install secure hash algorithms (SHA) tools, specifically SHA256 (as root)
      apt:
        state: latest
        pkg: ['hashalot']

    - name: install some X Window utilities (as root)
      apt:
        state: latest
        pkg: ['x11-apps', 'x11-xserver-utils', 'xterm', 'wmctrl']

    - name: install tools for viewing and manipulating image & video files (as root)
      apt:
        state: latest
        pkg: ['imagemagick', 'feh', 'mplayer']

    - name: install chromium-browser (as root)
      apt:
        state: latest
        pkg: ['chromium-browser']
  tags: ['never', 'install']     # 'never' implies you must pass the tag to execute this block

# --- Uninstall Block of Tasks -------------------------------------------------

- name: Uninstall Tools for Development Environment
  block:
    - name: uninstall chromium-browser (as root)
      apt:
        state: absent        # must be one of: absent, build-dep, fixed, latest, present
        autoclean: true      # cleans the local repository packages that can no longer be downloaded
        autoremove: true     # remove unused dependency with repository packages
        pkg: ['chromium-browser']
  tags: ['never', 'uninstall']   # 'never' implies you must pass the tag to execute this block

# ------------------------------------------------------------------------------

