---
- name: Verify
  hosts: all
  tasks:
    - name: Check if NGINX Plus is installed
      package:
        name: nginx-plus
        state: present
      check_mode: true
      register: install
      failed_when: (install is changed) or (install is failed)

    - name: Check if NGINX Plus service is running
      service:
        name: nginx
        state: started
        enabled: true
      check_mode: true
      register: service
      failed_when: (service is changed) or (service is failed)

    - name: Verify NGINX Plus is up and running
      uri:
        url: http://localhost
        status_code: 200
