
# role file to update all packages - equivalent to "apt update && apt full-upgrade"

---

tasks:
  - name: update repository cache
    apt:
      state: latest
      update_cache: true
      cache_valid_time: 86400

  - name: upgrade all packages
    apt:
      state: latest
      upgrade: dist

  - name: check if a reboot is needed because of kernel changes, etc.
    register: reboot_required_file
    stat:
      path: var/run/reboot-required
      get_md5: false

  - name: reboot the box if needed
    reboot:
      msg: "Reboot Initiated By Ansible"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: reboot_required_file.stat.exists

