
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# DESCRIPTION
#    Rol file for 'crypto-tools' role - install encryption and certificate packages
#
# TESTING
#    YAML linter to spot Ansible YAML syntax errors
#       yamllint rpi-loader.yml roles/crypto-tools/tasks
#       ansible-lint roles/crypto-tools/tasks/main.yml
#
#    Ansible linter to spot Ansible playbook syntax errors
#       ansible-playbook -i inventory -l test-pi rpi-loader.yml --syntax-check
#
#    Generate a list of tasks that will be executed for the tags
#       ansible-playbook -i inventory -l test-pi rpi-loader.yml --tags crypto-tools --skip-tags uninstall --list-tasks
#
#    Ansible dry-run checking for errors and showing results of a run
#       ansible-playbook -i inventory -l test-pi rpi-loader.yml --tags crypto-tools --skip-tags uninstall --check
#
# EXECUTION
#    Run the entire playbook for real
#       ansible-playbook -i inventory -l test-pi  rpi-loader.yml --tags crypto-tools --skip-tags uninstall
#
# SOURCES
#


---


# --- Install Block of Tasks ---------------------------------------------------

- name: Install Cryptography and Certificate Tools
  tags: ['never', 'install']     # 'never' implies you must pass the 'install' tag to execute this block
  block:
    - name: Install encryption and certificate packages (as root)
      ansible.builtin.apt:
        state: present           # must be one of: absent, build-dep, fixed, latest, present
        update_cache: true       # update the apt repository list cache
        cache_valid_time: 86400  # update the apt cache if it is older than this seconds
        pkg: ['apt-transport-https', 'ca-certificates', 'software-properties-common', 'gnupg', 'lsb-release']

    - name: Install secure hash algorithms (SHA) tools, specifically SHA256 (as root)
      ansible.builtin.apt:
        state: present           # must be one of: absent, build-dep, fixed, latest, present
        update_cache: false      # update the apt repository list cache
        pkg: ['hashalot']

# --- Uninstall Block of Tasks -------------------------------------------------

- name: Uninstall Cryptography and Certificate Tools (as root)
  tags: ['never', 'uninstall']   # 'never' implies you must pass the 'install' tag to execute this block
  block:
    - name: Message to user
      ansible.builtin.debug:
        msg: Nothing needs to be uninstalled, therefore, it is not

# ------------------------------------------------------------------------------

