---
- name: (SLES) Configure NGINX repository
  zypper_repository:
    name: "nginx-{{ nginx_branch }}"
    repo: "{{ nginx_repository | default(nginx_default_repository_suse) }}"
  when: nginx_manage_repo | bool

- name: (SLES) Install NGINX
  zypper:
    name: "nginx{{ nginx_version | default('') }}"
    state: "{{ nginx_state }}"
    disable_recommends: false
    update_cache: true
  ignore_errors: "{{ ansible_check_mode }}"
  notify: (Handler) Run NGINX
