
# task file for 'dev-tools' role - install useful devlopment utilities

---

- name: run the equivalent of "apt update"
  apt:
    state: latest
    update_cache: true
    cache_valid_time: 86400

- name: general development tools
  apt:
    name: ['gnome-terminal', 'screen', 'telnet', 'jq', 'markdown', 'vim-gtk3']
    state: latest

- name: software version control tools
  apt:
    name: ['git', 'git-lfs']
    state: latest

- name: install needed compilers
  apt:
    name: ['build-essential', 'cmake', 'unzip', 'pkg-config']
    state: latest

- name: install X windows libraries and OpenGL libraries
  apt:
    name: ['libxmu-dev', 'libxi-dev', 'libglu1-mesa', 'libglu1-mesa-dev']
    state: latest

- name: install optimization algorithums libraries
  apt:
    name: ['libopenblas-dev', 'libatlas-base-dev', 'liblapack-dev', 'gfortran']
    state: latest

- name: install HDF5 library for working with large datasets
  apt:
    name: ['libhdf5-serial-dev']
    state: latest

- name: install image and video libraries
  apt:
    name: ['libjpeg-dev', 'libpng-dev', 'libtiff-dev', 'libavcodec-dev', 'libavformat-dev', 'libswscale-dev', 'libv4l-dev', 'libxvidcore-dev', 'libx264-dev']
    state: latest

- name: install node.js and npm
  apt:
    name: ['nodejs', 'npm']
    state: latest

- name: secure hash algorithms (SHA) tools, specifically SHA256
  apt:
    name: ['hashalot']
    state: latest

- name: install some X Window utilities
  apt:
    name: ['x11-apps', 'x11-xserver-utils', 'xterm', 'wmctrl']
    state: latest

- name: tools for viewing and manipulating image & video files
  apt:
    name: ['imagemagick', 'feh', 'mplayer']
    state: latest

- name: python 3 development libraries including TK and GTK GUI support
  apt:
    name: ['python3-dev', 'python3-tk', 'python-imaging-tk', 'libgtk-3-dev', 'libboost-all-dev', 'python3-widgetsnbextension', 'python3-testresources', 'build-essential', 'cmake', 'python3-pip']
    state: latest
