
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# DESCRIPTION
#    Role file to install desirable and required prerequisites
#
# TESTING
#    YAML linter to spot Ansible YAML syntax errors
#       yamllint rpi-loader.yml roles/prerequisites/tasks
#       ansible-lint roles/prerequisites/tasks/main.yml
#
#    Ansible linter to spot Ansible playbook syntax errors
#       ansible-playbook -i inventory -l test-pi rpi-loader.yml --syntax-check
#
#    Generate a list of tasks that will be executed for the tags
#       ansible-playbook -i inventory -l test-pi rpi-loader.yml --tags prerequisites --skip-tags uninstall --list-tasks
#
#    Ansible dry-run checking for errors and showing results of a run
#       ansible-playbook -i inventory -l test-pi rpi-loader.yml --tags prerequisites --skip-tags uninstall --check
#
# EXECUTION
#    Run the entire playbook for real
#       ansible-playbook -i inventory -l test-pi  rpi-loader.yml --tags prerequisites --skip-tags uninstall
#
# SOURCES
#


---


# --- Install Block of Tasks ---------------------------------------------------

- name: Install Desirable and Required Prerequisites
  tags: ['never', 'install']     # 'never' implies you must pass the other tag to execute this block
  block:
    - name: Run the equivalent of "apt-get update" (as root)
      ansible.builtin.apt:
        update_cache: true       # update the apt repository list cache
        cache_valid_time: 86400  # update the apt cache if it is older than this seconds

    - name: Install required prerequisite packages (as root)
      ansible.builtin.apt:
        state: present
        name: ['git', 'curl', 'wget', 'ntp', 'apt-transport-https', 'gnupg2']

    - name: Install desirable prerequisite packages (as root)
      ansible.builtin.apt:
        state: present           # must be one of: absent, build-dep, fixed, latest, present
        update_cache: false
        pkg: ['ca-certificates', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Install these desirable packages for ansible, needed in some situations (as root)
      ansible.builtin.apt:
        state: present           # must be one of: absent, build-dep, fixed, latest, present
        update_cache: false
        pkg: ['acl']

    - name: Install these desirable packages for raspberry pi device interfaces (as root)
      ansible.builtin.apt:
        state: present           # must be one of: absent, build-dep, fixed, latest, present
        update_cache: false
        pkg: ['i2c-tools']

# --- Uninstall Block of Tasks -------------------------------------------------

- name: Uninstall Desirable and Required Prerequisites
  tags: ['never', 'uninstall']   # 'never' implies you must pass the other tag to execute this block
  block:
    - name: Message to user (as root)
      ansible.builtin.debug:
        msg: Nothing done. Packages newly installed and up-grades are unchanged.

# ------------------------------------------------------------------------------

