
# Execute on all of [nodes] in inventory
#     ansible-playbook -i inventory playbooks/vim-config.yml
#
# Execute on test-pi in inventory
#     cd ~/src/linux-tools/rpi-loader
#     ansible-playbook -i inventory -l test-pi playbooks/vim-config.yml
#
# See: https://www.redhat.com/sysadmin/ansible-configure-vim

---

- name: Configure Vim Terminal Visual Editor With Plugins
  hosts: all
  gather_facts: true
  become: false
  vars:
    install_status: absent     # for packages, use 'present' or 'latest' to install and 'absent' to remove
    vim_dir: /home/{{ ansible_user }}/.vim
    vimrc: /home/{{ ansible_user }}/.vimrc

  tasks:
    - name: install required packages to suport vim
      apt:
        state: '{{ install_status }}'
        update_cache: true
        cache_valid_time: 3600
        pkg:
          - vim
          - git
          - fzf

    - name: ensure .vim, .vim/autoload, .vim/bundle directories are created
      become_user: '{{ ansible_user }}'
      file:
        path: "{{ item }}"
        state: directory
        recurse: true
        mode: 0750
      loop:
        - "{{ vim_dir }}"
        - "{{ vim_dir }}/autoload"
        - "{{ vim_dir }}/bundle"

    - name: ensure pathogen is installed
      become_user: '{{ ansible_user }}'
      get_url:
        dest: "{{ vim_dir }}/autoload/pathogen.vim"
        url: https://tpo.pe/pathogen.vim

    - name: install plugins for vim
      become_user: '{{ ansible_user }}'
      git:
        dest: "{{ vim_dir }}/bundle/{{ item.name }}"
        repo: "{{ item.url }}"
        clone: true
        update: true
        recursive: true
      loop:
        - name: vim-airline
          url: https://github.com/vim-airline/vim-airline
        - name: nerdtree
          url: https://github.com/preservim/nerdtree
        - name: fzf-vim
          url: https://github.com/junegunn/fzf.vim
        - name: vim-gitgutter
          url: https://github.com/airblade/vim-gitgutter
        - name: vim-fugitive
          url: https://github.com/tpope/vim-fugitive
        - name: vim-floaterm
          url: https://github.com/voldikss/vim-floaterm

    - name: ensure .vimrc config in place
      become_user: '{{ ansible_user }}'
      copy:
        src: /home/jeff/src/vagrant-machines/ansible/vimrc
        dest: "{{ vimrc }}"
        force: true
        backup: true
        mode: 0640
