
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# role file to install resource file (.vimrc) and plugins for vi/vim editor
# See: https://www.redhat.com/sysadmin/ansible-configure-vim

# YAML linter to spot Ansible YAML syntax errors
#    yamllint playbook.yml roles/vim-config/tasks
#
# Ansible linter to spot Ansible playbook syntax errors
#    ansible-playbook -i inventory -l test-pi playbook.yml --syntax-check
#
# Ansible dry-run to understand what task will be executed without making changes
#    ansible-playbook -i inventory -l test-pi  playbook.yml --tags vim-config --skip-tags uninstall --list-tasks


---


# --- Install Block of Tasks ---------------------------------------------------

- name: Install Vim Terminal Visual Editor With Custom .vimrc and Plugins
  block:
    - name: install required packages to suport vim (as root)
      ansible.builtin.apt:
        state: present           # for packages, use 'present' or 'latest' to install and 'absent' to remove
        update_cache: true       # update the apt repository list cache
        cache_valid_time: 86400  # update the apt cache if it is older than this seconds
        pkg: ['stow', vim', 'vim-gtk3', 'libcanberra-gtk-module', 'libcanberra-gtk3-module', 'git']

    - name: clone the .vim github repository (as user)
      become_user: "{{ app_user }}"
      ansible.builtin.git:
        repo: 'http://github.com/jeffskinnerbox/.vim.git'
        dest: '{{ app_user_home }}/.vim'
        clone: true
        update: true    # perform an update on submodules in this git repository

    - name: create symbolic links for .vimrc and .gvimrc (as user)
      become_user: '{{ app_user }}'
      ansible.builtin.file:
        src: "{{ app_user_home }}/.vim/{{ item }}"
        dest: "{{ app_user_home }}/.{{ item }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        state: link
      loop:
        - vimrc
        # - gvimrc

    - name: ensure .vim/backup, .vim/tmp directories are created (as user)
      become_user: '{{ app_user }}'
      ansible.builtin.file:
        path: "{{ app_user_home }}/.vim/{{ item }}"
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        state: directory
        recurse: true
        mode: 0750     # mode 0750 = user can rwx, the group write, and others cannot read, write, or execute
      loop:
        - backup
        - tmp
  tags: ['never', 'install']     # 'never' implies you must pass the tag to execute this block

# --- Uninstall Block of Tasks -------------------------------------------------

- name: Uninstall Vim Terminal Visual Editor
  block:
    - name: remove all login vim related files & directories (as root)
      ansible.builtin.file:
        path: "{{ app_user_home }}/{{ item }}"
        state: absent
      loop: ['.vim', '.vimrc']
  tags: ['never', 'uninstall']   # 'never' implies you must pass the other tag to execute this block

# ------------------------------------------------------------------------------

