
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# role file to install ssh keys for Ansible useage
#
# YAML linter to spot Ansible YAML syntax errors
#    yamllint playbook.yml roles/ansible-ssh/tasks
#
# Ansible linter to spot Ansible playbook syntax errors
#    ansible-playbook -i inventory -l test-pi playbook.yml --syntax-check
#
# Ansible dry-run to understand what task will be executed without making changes
#    ansible-playbook -i inventory -l test-pi  playbook.yml --tags ansible-ssh --skip-tags uninstall --list-tasks
#

---

# - name: Install / Uninstall Ansible Controller SSH Authentication Access
#   hosts: all
#   become: true           # set to 'true' to activate privilege escalation => use sudo and be root by default
#   become_method: sudo
#   gather_facts: false
#
#   vars_prompt:
#     - name: "app_user"
#       prompt: "User name"
#       default: "pi"
#       private: false
#
#     - name: "app_user_password"
#       prompt: "Password"
#       default: "raspberry"
#       private: true
#       confirm: true
#
#   tasks:

# --- Install Block of Tasks ---------------------------------------------------

- name: install ssh key from host (as root)
  block:
    - name: create the user that will hold the key
      ansible.builtin.user:
        name: "{{ app_user }}"
        createhome: true
        state: present

    - name: setup ssh authorization for user (as root)
      ansible.posix.authorized_key:
        user: "{{ app_user }}"
        key: "{{ lookup('file', '{{ ansible_ssh }}') }}"
        state: present
  tags: ['never', 'install']     # 'never' implies you must pass the tag to execute this block

# --- Uninstall Block of Tasks ------------------------------------------------

- name: uninstall ssh key (as root)
  block:
    - name: set a 'pi' user account passward to default 'raspberry' (as root)
      ansible.builtin.user:
        name: "{{ app_user }}"
        password: "{{ app_user_password | password_hash('sha512') }}"
        state: present

    - name: setup ssh authorization for user (as root)
      ansible.posix.authorized_key:
        user: "{{ app_user }}"
        key: "{{ lookup('file', '{{ ansible_ssh }}') }}"
        state: absent
  tags: ['never', 'uninstall']     # 'never' implies you must pass the tag to execute this block

# ------------------------------------------------------------------------------

