
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# YAML linter to spot Ansible YAML syntax errors
#    yamllint deploy-ansible-ssh.yml roles/*/tasks
#
# Ansible linter to spot Ansible playbook syntax errors
#    ansible-playbook -i inventory -l test-pi deploy-ansible-ssh.yml --syntax-check
#
# Generate a list of tasks that will be executed for the tags
#    ansible-playbook -i inventory -l test-pi deploy-ansible-ssh.yml --tags install --list-tasks
#
# Ansible dry-run checking for errors and showing results of a run
#    ansible-playbook -i inventory -l test-pi deploy-ansible-ssh.yml --tags install --check
#
# Run the playbook for real
#    ansible-playbook -i <ip address>, deploy-ansible-ssh.yml --user pi --ask-pass --tags install
#    ansible-playbook -i inventory -l test-pi deploy-ansible-ssh.yml --user pi --ask-pass --tags install
#    ansible-playbook -i inventory -l test-pi deploy-ansible-ssh.yml --tags uninstall
#

---

- name: Install / Uninstall Ansible Controller SSH Authentication Access
  hosts: all
  become: true           # set to 'true' to activate privilege escalation => use sudo and be root by default
  become_method: sudo
  gather_facts: true

  vars_prompt:
    - name: "user_name"
      prompt: "User name"
      default: "pi"
      private: false

    - name: "user_password"
      prompt: "Password"
      default: "raspberry"
      private: true
      confirm: true

  tasks:

    # --- Install Block of Tasks -----------------------------------------------

    - name: install ssh key
      block:
        - name: create the user that will hold the key
          user:
            name: "{{ user_name }}"
            createhome: true
            state: present

        - name: setup ssh authorization for user
          authorized_key:
            user: "{{ user_name }}"
            key: "{{ lookup('file', '/home/jeff/.ssh/ansible.pub') }}"
            state: present
      tags: ['never', 'install']     # 'never' implies you must pass the tag to execute this block

    # --- Uninstall Block of Tasks ---------------------------------------------

    - name: uninstall ssh key
      block:
        - name: set a 'pi' user account passward to default 'raspberry'
          user:
            name: "{{user_name }}"
            password: "{{ user_password | password_hash('sha512') }}"
            state: present

        - name: setup ssh authorization for user
          authorized_key:
            user: "{{ user_name }}"
            key: "{{ lookup('file', '/home/jeff/.ssh/ansible.pub') }}"
            state: absent
      tags: ['never', 'uninstall']     # 'never' implies you must pass the tag to execute this block

