
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# Ansible's ping
#    ansible all -i inventory -m ping
#
# Run the playbook
#    ansible-playbook -i inventory ping.yml
#

---

- name: Test Ping
  hosts: all

  tasks:
  - action: ping
