
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# Ansible's ping
#    ansible all -i inventory -m ping
#
# Run the playbook
#    ansible-playbook -i inventory ping.yml
#

---

- name: Test Ping Each Host
  hosts: all
  become: true           # set to 'true' to activate privilege escalation => use sudo and be root by default
  become_method: sudo
  gather_facts: false

  tasks:
  - action: ping

