
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# While your within playbook directory, check the following prior to doing the play
#
# YAML linter to spot Ansible YAML syntax errors
#    yamllint playbook.yml roles/*/tasks
#
# Ansible linter to spot Ansible playbook syntax errors
#    ansible-playbook -i inventory -l test-pi playbook.yml --syntax-check
#
# Ansible dry-run to idenify tasks that are not tagged
#    ansible-playbook -i inventory -l test-pi  playbook.yml --tags untagged --list-tasks
#
# Ansible dry-run to understand what task will be executed without making changes
#    ansible-playbook -i inventory -l test-pi  playbook.yml --tags install --list-tasks
#
# Ansible dry-run to understand what task will be executed for a tag without making changes
#    ansible-playbook -i inventory -l test-pi  playbook.yml --tags install --list-tasks --tags "ups-pi, uninstall"
#
# Ansible dry-run checking for errors and showing results of a run without making changes
#    ansible-playbook -i inventory -l test-pi playbook.yml --tags install --check
#
# Run the entire playbook for real
#    ansible-playbook -i inventory -l test-pi playbook.yml --tags install
#
# Run just the role 'update' & 'dev-env' and skip the 'uninstall' tasks
#    ansible-playbook -i inventory -l test-pi playbook.yml --tags "update, dev-env" --skip-tags uninstall --list-tasks

---


- name: Install / Uninstall Raspberry Pi With Foundation Software
  hosts: all
  become: true           # set to 'true' to activate privilege escalation => use sudo and be root by default
  become_method: sudo
  gather_facts: true

  vars:
    # ----- used by all --------------------------------------------------------
    login_env_host: "test-pi"
    app_user: "pi"
    app_user_home: "/home/pi"
    tmp_path: /tmp                           # location for temporary files / executables

    # ----- used by docker -----------------------------------------------------
    docker_path: /usr/local/bin              # location for docker executables
    portainer_port: 9000
    portainer_agent_port: 9001
    portainer_data: portainer/data           # within 'app_user_home' path
    portainer_volumes: portainer/volumes     # within 'app_user_home' path

    # ----- used by apache -----------------------------------------------------
    http_host: "test-pi"
    http_conf: "test-pi.conf"
    http_port: "80"

    # ----- used by backup-user & rsnapshot & rsnapshot-container --------------
    backup_user: "backup_user"
    backup_user_home: "/home/backup_user"
    rsnapshot_store: "rsnapshot"             # root directory for rsnapshot data, files, tect
    rsnapshot_config: config                 # contains all relevant configuration files
    rsnapshop_source_data: zzz               # optional - storage location for data to be backed up
    rsnapshop_sink_data: xxx                 # optional - storage location for all snapshots

    # ----- used by duplicati --------------------------------------------------
    duplicati_port: 8270
    # duplicati_compose_path: "{{ backup_user_home }}/src/duplicati"
    # duplicati_config_path: "{{ duplicati_compose_path }}/config"
    # duplicati_compose_path: "/home/backup_user/src/duplicati"
    # duplicati_config_path: "/home/backup_user/src/duplicati/config"
    duplicati_config_path: "/home/backup_user/duplicati/config"
    duplicati_source_path: "/home/"


  tasks:
    - {import_role: {name: update}, tags: update}
    - {import_role: {name: ups-pi}, tags: ups-pi}                            # requires activation of i2c via 'sudo raspi-config'
    - {import_role: {name: prerequisites}, tags: prerequisites}
    - {import_role: {name: sys-env}, tags: sys-env}
    - {import_role: {name: net-tools}, tags: net-tools}
    - {import_role: {name: crypto-tools}, tags: crypto-tools}
    # - {import_role: {name: login-env}, tags: login-env}                      # replaced by 'dotfiles' role
    # - {import_role: {name: vim-config}, tags: vim-config}                    # replaced by 'dotfiles' role
    - {import_role: {name: dotfiles}, tags: dotfiles}
    - {import_role: {name: dev-env}, tags: dev-env}
    - {import_role: {name: dev-tools}, tags: dev-tools}
    - {import_role: {name: docker}, tags: docker}
    - {import_role: {name: apache}, tags: apache}
    - {import_role: {name: backup-user}, tags: backup-user}
    - {import_role: {name: deploy-ssh}, tags: deploy-ssh}
    - {import_role: {name: duplicati}, tags: duplicati}
    # - {import_role: {name: rsnapshot}, tags: rsnapshot}                      # not working yet
    # - {import_role: {name: rsnapshot-container}, tags: rsnapshot-container}  # not working yet

  # --- Handlers ---------------------------------------------------------------

  handlers:
    - name: reboot-host
      reboot:
        msg: "Ansible reboot triggered to finish install/uninstall tasks"
        pre_reboot_delay: 0       # seconds to wait before reboot
        post_reboot_delay: 30     # seconds to wait after the reboot command was successful before validate
        reboot_timeout: 600       # keep attempting to connect for 10 minutes (600 seconds)
        connect_timeout: 5        # disconnect after these seconds if ssh isn’t working, and try again
        test_command: whoami      # validate the node is up and working

    - name: start-apache
      service:
        name: apache2
        state: started

    - name: restart-apache
      service:
        name: apache2
        state: restarted

    - name: stop-apache
      service:
        name: apache2
        state: stopped

    - name: restart-ssh
      service:
        name: sshd
        state: restarted

    - name: restart-cron
      service:
        name: cron
        state: restarted

# ------------------------------------------------------------------------------

