
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# DESCRIPTION
#
# TESTING
#    YAML linter to spot Ansible YAML syntax errors
#       yamllint rpi-facts.yml
#       ansible-lint rpi-facts.yml
#
#    Ansible linter to spot Ansible playbook syntax errors
#       ansible-playbook rpi-facts.yml -i 192.168.1.79, --user pi --ask-pass --syntax-check
#
#    Generate a list of tasks that will be executed for the tags
#       ansible-playbook rpi-facts.yml -i 192.168.1.79, --user pi --ask-pass --list-tasks
#
#    Ansible dry-run checking for errors and showing results of a run
#       ansible-playbook rpi-facts.yml -i 192.168.1.79, --user pi --ask-pass --check
#
# EXECUTION
#    Run the playbook for real (assuming 'inventory' is up to date)
#       ansible-playbook rpi-facts.yml -i 192.168.1.79, --user pi --ask-pass
#
# VALIDATION
#    Execute this command to validate succesful provisioning (you should login withour a password)
#       ssh ansible@192.168.1.79
#
# SOURCES
#    https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html

---

- name: Print Facts About Server
  hosts: all
  become: true             # set to 'true' to activate privilege escalation => use sudo and be root by default
  become_method: sudo
  gather_facts: true

  tasks:

    - name: Filter facts gathered and return only selected facts
      ansible.builtin.setup:
        filter:
          - 'ansible_distribution'
          - 'ansible_machine_id'
          - 'ansible_*_mb'

