
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      0.0.5
#
# YAML linter to spot Ansible YAML syntax errors
#    yamllint playbooks/dev-env
#    ansible-playbook -i inventory playbooks/crypto-tools/crypto-tools.yml --check --tags install
#
# Ansible linter to spot Ansible playbook syntax errors
#    ansible-playbook -i inventory playbooks/crypto-tools/crypto-tools.yml --syntax-check
#
# Ansible dry-run checking for errors and showing results of a run
#    ansible-playbook -i inventory playbooks/crypto-tools/crypto-tools.yml --check --tags install
#

---

- name: Create your login environment on {{ login_env_host }}
  hosts: "{{ login_env_host }}"
  # remote_user: "{{ app_user }}"
  become: true                   # set to 'true' to activate privilege escalation => use sudo and be root by default
  become_method: sudo
  gather_facts: true
  vars_files:
    - vars/default.yml

  tasks:
    # --------------------------------------------------------------------------
    - name: Install cryptography and certificate tools
      block:
        - name: install encryption and certificate packages
          apt:
            state: latest            # must be one of: absent, build-dep, fixed, latest, present
            update_cache: true       # update the apt repository list cache
            cache_valid_time: 86400  # update the apt cache if it is older than this seconds
            pkg: ['apt-transport-https', 'ca-certificates', 'software-properties-common', 'gnupg', 'lsb-release']

        - name: install secure hash algorithms (SHA) tools, specifically SHA256
          apt:
            state: latest            # must be one of: absent, build-dep, fixed, latest, present
            update_cache: true       # update the apt repository list cache
            cache_valid_time: 86400  # update the apt cache if it is older than this seconds
            pkg: ['hashalot']
      tags: ['never', 'install']     # 'never' implies you must pass the 'install' tag to execute this block

    # --------------------------------------------------------------------------
    - name: Uninstall cryptography and certificate tools
      block:
        - name: message to user
          debug:
            msg: Nothing needs to be uninstalled, therefore, it is not
      tags: ['never', 'uninstall']   # 'never' implies you must pass the 'install' tag to execute this block

