
# Maintainer:   jeffskinnerbox@yahoo.com / www.jeffskinnerbox.me
# Version:      1.5.0
#
# task file for 'network-tools' role - install various networking related tools
#
# See: https://github.com/mrlesmithjr/ansible-network-tools

---


# --- Install Block of Tasks ---------------------------------------------------

- name: Install Networking Tools
  block:
    - name: install various networking tools / packages
      apt:
        state: latest            # must be one of: absent, build-dep, fixed, latest, present
        update_cache: true       # update the apt repository list cache
        cache_valid_time: 86400  # update the apt cache if it is older than this seconds
        pkg:
          - 'net-tools'
          - 'curl'
          - 'arp-scan'
          - 'arping'
          - 'arptables'
          - 'bmon'
          - 'dnsutils'
          - 'ifstat'
          - 'iftop'
          - 'iperf3'          # network performance testing & monitoring
          - 'iproute2'
          - 'lldpd'
          - 'lsof'
          - 'nbtscan'
          - 'netcat'
          - 'netdiscover'    # try 'sudo netdiscover -c 3 -s 10 -L -N -r 192.168.1.0/24'
          - 'netdiag'
          - 'nethogs'       # network performance testing & monitoring
          - 'netperf'
          - 'netsniff-ng'
          - 'net-tools'
          - 'nfdump'
          - 'ngrep'
          - 'nicstat'
          - 'nload'
          - 'nmap'
          - 'rfkill'
          - 'socat'
          - 'sysstat'         # display statistics about your cpu, i/o, network file system, etc.
          - 'tcpdump'
          - 'tcpflow'
          - 'tcpstat'
          - 'tcptrace'
          - 'tcptrack'
          - 'telnet'
          - 'traceroute'
          - 'ufw'            # installed but not enabled or configured
          - 'wavemon'
          - 'avahi-daemon'   # so you can discover hosts via Multicast Domain Name System (mDNS)

    - name: install encryption and certificate packages
      apt:
        state: latest          # must be one of: absent, build-dep, fixed, latest, present
        pkg: ['apt-transport-https', 'ca-certificates', 'software-properties-common', 'gnupg', 'lsb-release']

    - name: install useful formating tools
      apt:
        state: latest          # must be one of: absent, build-dep, fixed, latest, present
        pkg: ['jq']
  tags: ['never', 'install']   # 'never' implies you must pass the tag to execute this block

# --- Uninstall Block of Tasks -------------------------------------------------

- name: Uninstall networking tools
  block:
    - name: message to user
      debug:
        msg: Some, but not all, packages are being removed.

    - name: uninstall various networking tools / packages ... but not all
      apt:
        state: absent        # must be one of: absent, build-dep, fixed, latest, present
        autoclean: true      # cleans the local repository packages that can no longer be downloaded
        autoremove: true     # remove unused dependency with repository packages
        pkg:
          # - 'net-tools'
          # - 'curl'
          # - 'arp-scan'
          # - 'arping'
          # - 'arptables'
          - 'bmon'
          - 'dnsutils'
          - 'ifstat'
          - 'iftop'
          - 'iperf3'          # network performance testing & monitoring
          - 'iproute2'
          - 'lldpd'
          - 'lsof'
          - 'nbtscan'
          # - 'netcat'
          # - 'netdiscover'
          - 'netdiag'
          - 'nethogs'        # network performance testing & monitoring
          - 'netperf'
          - 'netsniff-ng'
          - 'net-tools'
          - 'nfdump'
          - 'ngrep'
          - 'nicstat'
          - 'nload'
          # - 'nmap'
          - 'rfkill'
          - 'socat'
          - 'sysstat'
          - 'tcpdump'
          - 'tcpflow'
          - 'tcpstat'
          - 'tcptrace'
          - 'tcptrack'
          - 'telnet'
          # - 'traceroute'
          # - 'ufw'
          - 'wavemon'
  tags: ['never', 'uninstall']   # 'never' implies you must pass the tag to execute this block

